### ISSUE TITLE
Impossible to pass "false" as training input value

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cli#1]
When I try to set `crop_based_on_salience` to `false`, I try:

```
replicate train stability-ai/sdxl input_images=@input-sprites.zip resolution=128 crop_based_on_salience=false caption_prefix="pixelart sprites in the style of TOK, " --destination=andreasjansson/sdxl-pixelart-sprites 
Training created: https://replicate.com/p/7tyxhvtboyeblkprtiulb6aeqm
```

The training doesn't actually include the `crop_based_on_salience` argument
<img width="639" alt="image" src="https://github.com/replicate/cli/assets/713993/1d05779d-3c46-48ce-95b4-e2c8acc9b543">

**Comment by mattt** [comment]
@andreasjansson I spent a while chasing this down only to realize that the issue was in how training inputs are rendered on the website. If you do `curl https://api.replicate.com/v1/predictions/7tyxhvtboyeblkprtiulb6aeqm | jq`, you should see `crop_based_on_salience` set to `false` in the inputs for the training.

**Comment by mattt** [comment]
See also https://github.com/replicate/replicate-python/issues/140
